
version: "3"

services:
  filebrowser:
    build: .
    restart: unless-stopped
    environment:
      # database connection
      DB_DRIVER_NAME: "sqlite" #"mysql+mysqldb"
      # DB_USERNAME: ""
      # DB_PASSWORD: ""
      # DB_HOST: ""
      DB_DATABASE: "./db/db.sqlite3"
      # Application settings
      APP_IP: "0.0.0.0"
      APP_TRUSTED_HOSTS: "127.0.0.1" # hosts that can use this API, use * to accept any, ommiting this flag also se as *
      # log settings
      LOG_LEVEL: "DEBUG"
      LOG_ROTATION: "00:00"
      LOG_RETENTION: "30 days"
      LOG_COMPRESSION: "zip"
      # email settings
      EMAIL_ENABLED: "0"
      EMAIL_USERNAME: ""
      EMAIL_PASSWORD: ""
      EMAIL_SMTP_HOST: ""
      EMAIL_SMTP_PORT: ""
      # other settings
      GET_ADDRESS_FROM_VIACEP: 0 # 0=false, 1=true
    volumes:
      - ./container/logs:/code/app/logs
      - ./container/db:/code/db
    ports:
      - 50000:5000
      